Restore cjs config extension
facebook/relay pull request #3861
Opened 2022-04-06 19:48 UTC by zth

This restores `relay.config.cjs` as a potential target for the config autosearch the compiler CLI does. 

Rationale: `cjs` is an increasingly common config format now that projects like Vite are helping people move to ES modules.

2022-04-07 06:46 UTC, captbaritone commented
Seems reasonable to me. I'll import in the morning.

2022-04-08 20:26 UTC, alunyov requested changes
Thanks!

I think we need to add support for this in a few more places:
- https://github.com/facebook/relay/blob/7c68fc77c86c8a7a81641da9e81ee46dc48f1fa6/packages/babel-plugin-relay/BabelPluginRelay.js#L18-L23
- https://github.com/facebook/relay/blob/7c68fc77c86c8a7a81641da9e81ee46dc48f1fa6/compiler/crates/relay-compiler/src/config.rs#L179

2022-04-11 12:13 UTC, zth commented on compiler/crates/relay-compiler/src/config.rs
> +                LoaderSource::Js("relay.config.cjs".to_string()),
I don't think so, at least not initially. But let me look that up properly first.

2022-04-11 12:13 UTC, zth commented
> Thanks!
> 
> I think we need to add support for this in a few more places:
> 
> * https://github.com/facebook/relay/blob/7c68fc77c86c8a7a81641da9e81ee46dc48f1fa6/packages/babel-plugin-relay/BabelPluginRelay.js#L18-L23
> * https://github.com/facebook/relay/blob/7c68fc77c86c8a7a81641da9e81ee46dc48f1fa6/compiler/crates/relay-compiler/src/config.rs#L179

Thanks! I'll fix the remaning places soon, bear with me 😄

2022-04-12 20:11 UTC, kassens commented
I was actually thinking we should deprecate the `.js` version completely as it's currently shelling out to `node` in the path without much thought if specific environment variables need to be set etc.

This would just leave standalone `.json` and embedded within `package.json`. Is that insufficient?

2022-04-13 07:21 UTC, zth commented
I don't think dropping `.js` support is desirable at this moment, for that same reason. I know plenty of people that are emulating "dynamic build configs" using environment variables like described above too.

I do think having JSON configuration be the officially recommended way is good. Just not getting rid of JS config completely.

2025-07-22 11:45 UTC, closed without merging