support sha256 and md5 algos for local file persister
facebook/relay pull request #3878
Opened 2022-04-16 01:29 UTC by tbezman

Coinbase needs to use SHA256 . We temporarily have been using a custom persist server that devs run locally. Would be nice to have it in the compiler. 

I also threw MD5 in here while I was at it.

2022-04-18 15:05 UTC, alunyov requested changes
Thanks @tbezman!

I like the rust part.

What do you think about keeping the example persist script/server? But still adding the new section `Local Persisted Queries`.

2022-04-26 14:11 UTC, tbezman commented
@alunyov Okay, I've added back the local persist server example. Let me know if we need any other changes?

2022-04-26 15:09 UTC, alunyov approved these changes

2022-04-28 16:35 UTC, closed without merging

2022-06-10 12:28 UTC, eMerzh commented
Sorry for chiming in after the fact ... 

But this is really great :) 

Do you think it would be possible to do that without using the "persistor" thing ? 
like changing the cacheId in the opreations, but still have access to the operation's text ?

thanks