Use `import type` in typescript for all imports
facebook/relay pull request #4029
Opened 2022-07-26 06:29 UTC by tomgasson

This makes the following changes to typescript artifacts:

```diff
-import { ConcreteRequest, Query } from "relay-runtime";
+import type { ConcreteRequest, Query } from "relay-runtime";
 import type { FragmentRefs } from "relay-runtime";
```

Using the existing `useImportTypeSyntax` config.

As stated in the config, the `import type` syntax introduced in Typescript version 3.8 and prevents warnings from `importsNotUsedAsValues`. This setting also assists naive bundlers from taking a dependency on `relay-runtime`, when only the types are needed.

I kept this simple. Other paths for implementation would be
 - There's a mix of distinct typegen printers e.g. compiler/crates/relay-typegen/src/typescript.rs, and the inline use of conditionals on the language directly in compiler/crates/relay-compiler/src/artifact_content/content.rs. Consolidating these would allow sharing the existing `write_import_type` function
 - The imports could instead be consolidated and printed together, rather than potentially having multiple imports from the same file as it is now

2022-07-28 16:40 UTC, alunyov requested changes
Thank you for PR! This looks good to me! 

Can you add a test for these changes?

2022-08-03 15:08 UTC, tomgasson commented
Removed the missing newline at EOF, because I'm guessing that was the internal lint warning

2022-08-03 15:11 UTC, alunyov commented
Hmm, @tomgasson for some reason this breaks one of the internal typescript tests (we should probably move these to OSS)

It removes the import type of `ConcreteRequest` and `Query`...

```
/* eslint-disable */
 // [@ts](https://www.internalfb.com/intern/profile/ts)-nocheck
 
-import { ConcreteRequest, Query } from 'relay-runtime';
```

2022-08-03 15:16 UTC, tomgasson commented
Hmmm. Are those tests using `use_import_type_syntax`? Is the output _after_ stripping types / building typescript artifacts? That kind of the purpose of this change - to not have a _value_ import in the code actually sent to browsers

 It's a bit hard to see how this change would remove something if it's only the relay generated output

2022-09-30 16:23 UTC, closed without merging