adding support for client extensions in mock payload generator
facebook/relay pull request #4030
Opened 2022-07-27 14:53 UTC by stewartavery

## Problem
At Twitter we've been hoping to use MockPayloadGenerator to allow us to scaffold data in tests/[stories](https://storybook.js.org/) while our components use client side schema extensions. One of the engineers on my team discovered that this support is explicitly disallowed in the `relay` repo. I reached out to the discord channel and received feedback that enabling this would make sense.

## Solution
Within `RelayMockPayloadGenerator.js`, modify the logic within `_traverseSelections` to recursively traverse the nested selections. This places the logic alongside `DEFER` and `STREAM`. 

A snapshot was updated as a result of this change —  local client extension `client_name` and `client_code` now have generated mocked fields.

2022-07-27 15:05 UTC, sibelius approved these changes

2022-07-28 16:37 UTC, alunyov requested changes
Thank you for submitting PR!

I think it make sense to enable the payload generation for client extension for your use case.
From the discord:

> In our case we're populating using environment.commitPayload before the query. So that works fine when we're writing tests for the component that is executing the query (the top level component). Where we have a tougher time is when there's a sub component that we may want to create a test for that also uses the client side field. We'll then create a query wrapper to create a story/test for that component. But at that point we need to be aware of the client side field and do the hydration manually in the story/test. 

In order to preserve the current behavior (see https://www.hyrumslaw.com/) of the API what do you think about adding a new method to the API:  `generateWithClientData(..)`?

We also need to update compiler transform to include client fields in the @relay_test_operation: https://github.com/facebook/relay/blob/df2c9965896d670d59ddaf08132b0ab778424b6a/compiler/crates/relay-transforms/src/test_operation_metadata.rs#L221 (this can be done in a separate PR)

2022-07-28 17:15 UTC, stewartavery commented
@alunyov You're totally right! I'll see if I can find some time to follow up to make that change

2022-07-28 17:24 UTC, stewartavery commented
What are your thoughts on extending the private methods in the class, something like:

```js
generateWithClientData(
    selections: $ReadOnlyArray<NormalizationSelection>,
    operationType: string,
  ): MockData {
    const defaultValues = this._getDefaultValuesForObject(
      operationType,
      null,
      null,
      [], // path
      {},
    );
    return this._traverse(
      {
        selections,
        typeName: operationType,
        isAbstractType: false,
        name: null,
        alias: null,
        args: null,
      },
      [], // path
      null, // prevData
      defaultValues,
      true, // isClientExtensionGenerated <--- __traverse would receive a new argument here
    );
  }
```

and then we'd check that condition above when evaluating `__traverse` at the `CLIENT_EXTENSION` evaluation?

2022-07-28 17:37 UTC, stewartavery commented
Or I could add an optional arg to `generate`. and have `generateWithClientData` call `generate` with a truthy value in the arg?

2022-07-28 21:59 UTC, alunyov commented
I would keep public version of `generate` unchanged (without adding options), and add a new public method `generateWithClientData`.

And internally, in this module we an pass this flag to the `generateData` function here:

https://github.com/facebook/relay/blob/d59b18320aa5656ca907ed11c71477bc160fed09/packages/relay-test-utils/RelayMockPayloadGenerator.js#L849-L854

And then in can be a property of the class:

https://github.com/facebook/relay/blob/d59b18320aa5656ca907ed11c71477bc160fed09/packages/relay-test-utils/RelayMockPayloadGenerator.js#L176-L180

something like `_shouldGenerateClientData`.

2022-08-07 18:01 UTC, stewartavery commented
Hey @alunyov, finally managed to get around to making this change! let me know if this is what you had in mind

2022-08-12 14:07 UTC, alunyov requested changes
Looks good!
I have one small suggestion.

2022-08-12 14:07 UTC, alunyov commented on packages/relay-test-utils/__tests__/RelayMockPayloadGenerator-test.js
> +  isClientDataMocked: ?boolean = false,
nit: can we make this argument an object `options` or something like that...


```
options: ?{
   mockClientData?: boolean
}
```

2022-08-12 14:56 UTC, stewartavery commented
@alunyov cool, just pushed another change! also standardized on the `clientDataMocked` name across other files

2022-08-12 16:05 UTC, alunyov approved these changes

2022-08-17 22:51 UTC, closed without merging