Bump version of VSCode extension, update README
facebook/relay pull request #4127
Opened 2022-11-15 17:58 UTC by ernieturner

Does a major bump of the VSCode extension and adds new configuration options to README. I did a major version bump because (from what I could tell) the old `config.rootDirectory` and `config. pathToConfig` aren't taken into account, so this would likely break for users upgrading.

2022-11-28 18:49 UTC, captbaritone requested changes

2022-11-30 18:32 UTC, ernieturner commented
@captbaritone Did some re-organizing and cleanup of the config section to hopefully make it more clear how each of the config options works depending on single vs multiple.

2022-12-19 19:05 UTC, closed without merging

2022-12-20 15:32 UTC, ernieturner commented
@captbaritone We should be able to kick off https://github.com/facebook/relay/actions/workflows/vscode.yml now right?

2023-01-03 17:51 UTC, captbaritone commented
Sorry for the delay, I've been out of office. I just tried kicking it off and got a failure related to a version mismatch. Looking into it now.

https://github.com/facebook/relay/actions/runs/3831747693/jobs/6521246260

2023-01-03 18:01 UTC, ernieturner commented
No worries! I just pushed up [this PR](https://github.com/facebook/relay/pull/4166) to bump the vscode engine which might fix this?

2023-01-03 19:23 UTC, captbaritone commented
Looks like the publish failed for a new reason: https://github.com/facebook/relay/actions/runs/3832309035

I suspect it has something to do with caching node_modules? Going to look into if we can run without cache.

2023-01-03 20:20 UTC, captbaritone commented
I'm able to reproduce the issue locally:

```
cd vscode-extension
yarn install --frozen-lockfile --ignore-scripts
yarn vsce publish
```

It errors with the conflicts before it tries to publish and realizes it has no auth.

The error seems to come from here: https://github.com/microsoft/vscode-vsce/blob/8b49e9dfdf909ad3af2b9ec9c825f5b501f6d75e/src/package.ts#L1179

I added some logging and it seems like it's not actually a case sensitivity issue, but rather that the files are getting processed twice for some reason. (This aligns with the logging which shows the files having the same case).

I'm out of time to investigate today. @ernieturner  would you be able to take a look?

2023-01-04 17:52 UTC, ernieturner commented
@captbaritone I think I have this working, but in the middle of testing it out I realized that [the multi-config PR](https://github.com/facebook/relay/pull/3972) hasn't actually landed in this repo yet. It looks like those changes have been imported but hasn't merged. Can we get that fixed up first, then I'll put up a PR to fix the publishing step?